/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itcmgrfct;

import java.awt.Desktop;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Subhodeep
 */
public class ManuelViewer extends javax.swing.JFrame {

    /**
     * Creates new form ManuelViewer
     */
    public ManuelViewer() {
        initComponents();
        jComboBox1.disable();
        jComboBox3.disable();
        jComboBox4.disable();
        jButton1.hide();
        jButton2.setEnabled(false);
        manuel.setVisible(false);
        filetype.setVisible(false);
        go.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        filetype = new javax.swing.JLabel();
        go = new javax.swing.JLabel();
        manuel = new javax.swing.JLabel();
        dept = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manuel Store");
        setLocation(new java.awt.Point(510, 200));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 255, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setBackground(new java.awt.Color(204, 204, 255));
        jComboBox1.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "InstructionManuel", "OperatingManuel", "MaintainenceManuel" }));
        jComboBox1.setSelectedIndex(-1);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 170, 33));

        jComboBox2.setBackground(new java.awt.Color(204, 204, 255));
        jComboBox2.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PMD", "SMD", "ENG", "COM", "SECURITY", "EHS", "HR", "MIS" }));
        jComboBox2.setSelectedIndex(-1);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 170, 33));

        jComboBox3.setBackground(new java.awt.Color(204, 204, 255));
        jComboBox3.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PDF", "Video", "Image" }));
        jComboBox3.setSelectedIndex(-1);
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 170, 33));

        jComboBox4.setBackground(new java.awt.Color(204, 204, 255));
        jComboBox4.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jPanel1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 470, 40));

        jButton1.setText("AutoSearch");
        jButton1.setEnabled(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 104, -1));

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        jButton2.setText("OPEN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 310, 90, 40));

        filetype.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        filetype.setForeground(new java.awt.Color(204, 204, 255));
        filetype.setText("View What ?");
        jPanel1.add(filetype, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 120, -1));

        go.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        go.setForeground(new java.awt.Color(204, 204, 255));
        go.setText("Almost Ready... Choose one and hit the button...");
        jPanel1.add(go, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 480, -1));

        manuel.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        manuel.setForeground(new java.awt.Color(204, 204, 255));
        manuel.setText("Which Manuel ?");
        jPanel1.add(manuel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 150, -1));

        dept.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        dept.setForeground(new java.awt.Color(204, 204, 255));
        dept.setText("Which Department ?");
        jPanel1.add(dept, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 200, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itcmgrfct/ITCEVLogo.jpg"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 190, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 883, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        class AutoSearch extends Thread{
            public AutoSearch(){
                setPriority(MAX_PRIORITY);
            }
        @Override        
        public void run()
        { 
            jComboBox4.removeAllItems();
        String mt = String.valueOf(jComboBox1.getSelectedItem());
        String d1 = String.valueOf(jComboBox2.getSelectedItem());
        String ft1 = String.valueOf(jComboBox3.getSelectedItem());
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection c = DriverManager.getConnection("jdbc:sqlserver://127.0.0.1:1433;DatabaseName=ITCDatabase;","sa","deep");
            Statement s = c.createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM "+mt+"");
            while(rs.next())
            {
                String d = rs.getString("Dept");
                String ft = rs.getString("Filetype");
                if((d.equals(d1)) && (ft.equals(ft1)))
                {
                    String onlyfilename = rs.getString("Filepath").substring(rs.getString("Filepath").lastIndexOf("\\")+1);
                    jComboBox4.addItem(onlyfilename);
                }
            }
            c.close();
        } catch (Exception e) {JOptionPane.showMessageDialog(dad, e.getMessage());}
        }
        }
        
        new AutoSearch().start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      class View extends Thread{   
          @Override
          public void run()
        {
            try {
                String d1 = String.valueOf(jComboBox2.getSelectedItem());
                String mt = String.valueOf(jComboBox1.getSelectedItem());
                String f = String.valueOf(jComboBox4.getSelectedItem());
                Desktop.getDesktop().open(new File("F:\\ITCMANUELS\\"+d1+"\\"+mt+"\\"+f));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(dad, "No Manuel to View","Error",JOptionPane.INFORMATION_MESSAGE); }
        }
      }  
        new View().start();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        jButton1.setEnabled(true);
        jButton1.doClick();
        jButton1.setEnabled(false);
        go.setVisible(true);
        jComboBox4.enable();
        jButton2.setEnabled(true);
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        manuel.setVisible(true);
        jComboBox1.enable();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        filetype.setVisible(true);
        jComboBox3.enable();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManuelViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManuelViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManuelViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManuelViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManuelViewer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dept;
    private javax.swing.JLabel filetype;
    private javax.swing.JLabel go;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel manuel;
    // End of variables declaration//GEN-END:variables
public ManuelViewer dad;
}
